version: '3.8'

services:
  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=controle
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql

volumes:
  mysql_data: